version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/packages/frontend/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/packages/smart-contracts/"
  schedule:
    interval: monthly
    time: "22:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/packages/subgraph/"
  schedule:
    interval: monthly
    time: "23:00"
  open-pull-requests-limit: 10
